main/urls.py
from django.conf.urls import url

from .views import * 

urlpatterns = [
	url(r'^$', index, name='learninghome'),
    url(r'^(?P<subjectslug>[-\w]+)/$', Videolist, name='videolist'),
    url(r'^(?P<subjectslug>[-\w]+)/(?P<chapterslug>[-\w]+)/(?P<videoslug>[-\w]+)/$', VideoPerSubject, name='videodetail'),
]

onlinelearning/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import main.views as mainviews

urlpatterns = [
	url(r'^$',mainviews.index, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^learning/', include('main.urls', namespace='main')),
]

main/models.py
from django.db import models
from django.template.defaultfilters import slugify

from urllib.parse import urlparse, parse_qs

# Create your models here.


class Subjects(models.Model):
	name = models.CharField(max_length = 50)
	description = models.CharField(max_length = 300)
	slug = models.SlugField(max_length = 100, editable=False)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if self.slug is None or self.slug == '':
			self.slug = slugify(self.name)

		i = 0
		while True:
			slug_count = Subjects.objects.filter(
				slug__exact=self.slug).exclude(pk=self.pk)
			if not slug_count:
				break
			else:
				i += 1
				self.slug = self.slug + str(i)

		super(Subjects, self).save(*args, **kwargs)


class Chapters(models.Model):
	name = models.CharField(max_length=50)
	slug = models.SlugField(max_length=100, editable=False, unique=True)
	subject = models.ForeignKey('Subjects', on_delete=models.CASCADE, 
		related_name="chapters")

	def __str__(self):
		return self.subject.name +":"+self.name

	def save(self, *args, **kwargs):
		if self.slug is None or self.slug == '':
			self.slug = slugify(self.name)

		i = 0
		while True:
			slug_count = Chapters.objects.filter(
				slug__exact=self.slug).exclude(pk=self.pk)
			if not slug_count:
				break
			else:
				i += 1
				self.slug = self.slug + str(i)

		super(Chapters, self).save(*args, **kwargs)


class Videos(models.Model):
	name = models.CharField(max_length=100)
	slug = models.SlugField(max_length=300, editable=False, null=True)
	description = models.TextField(blank=True, null=True)
	youtubeurl = models.URLField()
	youtubevid = models.CharField(max_length=16, editable=False, null=True)
	chapter = models.ForeignKey('Chapters', on_delete = models.CASCADE)

	def __str__(self):
		return self.chapter.subject.name+":"+\
		self.chapter.name + ":" +self.name

	def save(self, *args, **kwargs):
		if self.youtubevid is None or self.youtubevid == '':
			if self.youtubeurl:
				parsed = urlparse(self.youtubeurl)
				try:
					self.youtubevid = parse_qs(parsed.query)['v'][0]
				except:
					pass


		if self.slug is None or self.slug == '':
			self.slug = slugify(self.name)

		i = 0
		while True:
			slug_count = Videos.objects.filter(chapter=self.chapter).filter(
				slug__exact=self.slug).exclude(pk=self.pk)
			if not slug_count:
				break
			else:
				i += 1
				self.slug = self.slug + str(i)

		super(Videos, self).save(*args, **kwargs)

main/views.py
from django.shortcuts import render
from .models import Subjects, Videos, Chapters

# Create your views here.

def index(request):
	template = 'main/index.html'

	subjects = Subjects.objects.all()


	context = {
	'subjects': subjects,
	}

	return render(request, template, context)


def VideoPerSubject(request,subjectslug,chapterslug,videoslug):
	template = 'main/videolist.html'

	subject = Subjects.objects.get(slug=subjectslug)
	chapter = subject.chapters.get(slug=chapterslug)
	video = chapter.videos_set.get(slug=videoslug)

	context = {
	'subject': subject,
	'video': video,
	}

	return render(request, template, context)

def Videolist(request,subjectslug):
	template = 'main/videolist.html'

	subject = Subjects.objects.get(slug=subjectslug)
	chapter = subject.chapters.all()[:1].get()
	video = chapter.videos_set.all()[:1]

	context = {
	'subject': subject,
	'video': video,
	}

	return render(request, template, context)

main/templates/main/index.html
{% extends 'base.html' %}
{% load i18n %}

<style>
	{% block style %}
	.subjectblock {
		background-color: #f1f1f1;
		height: 200px;		
	}

	.subjectblock:hover {
		box-shadow: 0 2px 4px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12)!important;
	}

	{% endblock %}
</style>


{% block content %}
{% include 'navbar.html' %}

<div class="jumbotron text-center bg-info" id="jumbotron">
	<h1> {% trans 'Welcome' %}</h1>
</div>

<div class="container my-4" id="subject">
	<div class="row">
		
	{% for subject in subjects %}
	<a href="{% url 'main:videolist' subject.slug %}" class="col-md-4 col-sm-6">
		<div class="my-2 mp-2 subjectblock text-center">
			<h3> {{subject.name}} </h3>
			<p>{{ subject.description }}</p>
		</div>
	</a>

	{% endfor %}
	</div>

</div>
{% endblock %}

main/templates/main/snippets/sidebar.html
{% comment %}
side nav bar for each class 
input: subject


{% endcomment %}
<nav id="sidebar">
	<div class="siderbar-hearder">
		<h3> {{subject.name}} </h3>
	</div>
	<div class="list-group text-center text-md-left">
		{% for chapter in subject.chapters.all %}
		<a href="#chapter{{forloop.counter}}" class="list-group-item justify-content-between" data-toggle="collapse" aria-expanded="false">{{chapter.name}}<span class="badge badge-default badge-pill">{{chapter.videos_set.all.count}} Videos</span></a>
		<div class="collapse" id="chapter{{forloop.counter}}">
			{% for video in chapter.videos_set.all %}
			<a href="{% url 'main:videodetail' subject.slug chapter.slug video.slug %}" class="pl-5 list-group-item list-group-item-success">{{video.name}}</a>
			{% endfor %}
		</div>
		{% endfor %}
	</div>
	
</nav>

<script type="text/javascript">
	$('a.list-group-item').each(
		function(){
			if ($(this).attr('href') == '{{request.path}}') {
				$(this).toggleClass('active');
				$(this).parent().toggleClass('show')
			}
		})
</script>

main/templates/main/snippets/subjectblock.html
{% comment %} 
the style of one block of subject
input:  title,description

{% endcomment %}

<h3>
	{{title}}
</h3>
<p>
	{{description}}
</p>

main/templates/main/videolist.html
{% extends 'base.html' %}
<style type="text/css">
{% block style %}


{% endblock %}
</style>


{% block content %}
{% include 'navbar.html' %}

<h1>{{subject.name}}</h1>

<div class="container-fluid">

	<div class="row">

		<div class="col-lg-2 col-md-3 bg-faded px-0">
			{% include 'main/snippets/sidebar.html' with subject=subject %}
		</div>

<!-- 		<nav id="sidebar" class="col-lg-2 col-md-4 bg-faded">
		<ul>
		{% for video in videos %}
			<li>{{video.name}}</li>
		{% endfor %}
		</ul>
			
		</nav> -->

		<div id="video" class="col-lg-10 col-md-9 px-0">
			<div class="embed-responsive embed-responsive-16by9">
			<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{video.youtubevid}}?rel=0" allowfullscreen></iframe>
			</div>
			<div>
				<h2>{{video.name}}</h2>
				<p>{{video.description}}</p>
			</div>
		</div>
		
	</div>
	
</div>

{% endblock %}

templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block description %} {% endblock%}">
    <meta name="author" content="Lina Cao">

    <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    
    <link rel="icon" href="{% static 'img/logo_thumb.jpg' %}" >

    <title>
      {% block title %}
      {% endblock %} {% trans 'online learning' %} 
    </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block header %}

    {% endblock %}
    
    <style>
    {% block style %}
    {% endblock %}
    </style>


    <!-- Custom styles for this template -->
  </head>

  <body>


  {% block content %}
  {% endblock %}

  {% if messages %}
  <ul>
  {% for message in messages %}
  <li>{{ message }} </li>
  {%endfor %}
  </ul>
  {% endif %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js'%}"></script>
<script>
    {% block script %}
    {% endblock %}
</script>

  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-toggleable-sm navbar-light bg-faded" id="headerNav">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarc" aria-controls="navbarc" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarc">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"> <a href="{% url 'home' %}">Home</a></li>
         
    </ul>

    <ul class="navbar-nav pull-md-right">
   {% if request.user.is_staff%}
    <li class="nav-item">          
     <a class="nav-link btn btn-primary" href="{% url 'admin:index' %}"> AdminPage </a>
    </li>
        {% endif %}
          <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>


    </ul>

  </div>
</nav>